### ISSUE TITLE
Induction

### ISSUE THREAD

**Issue by OlingCat** [Agda-zh/PLFA-zh#15]
- [x] 初译
- [x] 初校

**Comment by fangyi-zhou** [comment]
fcd86e99eca3e3bc3fb75a9225ab00a174434680 加入了一些新的内容 需要重新补一下

**Comment by OlingCat** [comment]
> [fcd86e9](https://github.com/Agda-zh/PLFA-zh/commit/fcd86e99eca3e3bc3fb75a9225ab00a174434680) 加入了一些新的内容 需要重新补一下

补上了

**Comment by inkydragon** [comment]
https://github.com/Agda-zh/PLFA-zh/blob/56bb391e805dd80dcd6dbfeeb86477eebd869223/src/plfa/Induction.lagda#L101

> 分配率（Distributivity）

这个 google 搜了，去查词典竟然很难查到，找到一个

> the quality of being distributive
> - [Distributivity 释义 | 柯林斯英语词典](https://www.collinsdictionary.com/zh/dictionary/english/distributivity)

这个确实能叫做 ”分配率“。

不过看定义 ”Distributivity“ 指的就是 “distributive law“。

而原文又说
> mathematicians have agreed on names for some of the most common **properties**.

不如翻译为 ”分配**性**“吧。其他的几个词也可以改一改，都改成 ”XX性“，毕竟都是运算符的性质。”XX律“对应的应该是 "xxxx law"

> Identity 同一性
> Associativity 结合性
> Commutativity 交换性
> Distributivity 分配性
