### ISSUE TITLE
Quantifiers 一章的一个翻译错误

### ISSUE THREAD

**Issue by roife** [Agda-zh/PLFA-zh#151]
https://github.com/Agda-zh/PLFA-zh/blob/dev/src/plfa/part1/Quantifiers.lagda.md?plain=1#L353

此处写道“积是依赖积的一种特殊形式”，原文为“Products arise as a special case of existentials”。

应该更正为“积是存在量词的一种特殊形式”。

**Comment by fangyi-zhou** [comment]
感谢指正！
