### ISSUE TITLE
代码中的链接跳转不正确

### ISSUE THREAD

**Issue by OlingCat** [Agda-zh/PLFA-zh#37]
官方文档中会自动在代码内跳转链接前加上 `https://agda.github.io/agda-stdlib/` 前缀，而我们的文档由于没有任何前缀会导致跳转时在当前 URL 下寻找文档。有人知道生成文档这块是哪里控制的吗？

**Comment by roger-uw** [comment]
生成文档是由 agda2html 控制的，如果要链接到 agda-stdlib，需要添加 `--link-to-agda-stdlib` 这个flag，而这在 Makefile 中配置为在 `make build` 和 `make build-incremental` 时才添加。最开始翻译的时候，因为 [html-proofer 说各种链接都坏掉了](https://github.com/gjtorikian/html-proofer/issues/266)，所以我在 .travis.yml 中只使用了最基本的 `make build-offline`，导致了 `--link-to-agda-stdlib` 未被添加。

**Comment by roger-uw** [comment]
修复： #38 
除了链接到 agda-stdlib，也解决了 html-proofer 的问题。

**Comment by roger-uw** [comment]
目前跳转到的 `https://agda.github.io/agda-stdlib/` 页面似乎还是和代码对应不上，不过这个问题在原书也存在。
