### ISSUE TITLE
两个网站不一致问题

### ISSUE THREAD

**Issue by OlingCat** [Agda-zh/PLFA-zh#52]
https://plfa-zh.github.io/ 和 https://agda-zh.github.io/PLFA-zh/ 的显示并不一致，但差不多都是同一时间部署的。https://plfa-zh.github.io/ 看起来更旧一些，似乎用了旧的缓存？

~~咱注意到 https://github.com/Agda-zh/PLFA-zh/blob/dev/.travis.yml 里对两个 repo 的部署用到了同一个 GITHUB_TOKEN，应该是现在这个 repo 的。我们似乎应该给 https://github.com/plfa-zh/plfa-zh.github.io 再生成一个 Token？~~

好吧跟 GITHUB_TOKEN 无关。

有人问这两个 URL 访问哪一个才对？为避免混乱，或许我们应该只保留 https://plfa-zh.github.io/ ，本 repo 不再开启 GitHub Pages 并删除 master 分支。

@roger-uw

**Comment by roger-uw** [comment]
我之前注意到过这个问题，以为是 _config.yml 配置不当导致的，也尝试解决过（ #43 ），但并没有起到效果。在 https://github.com/plfa-zh/plfa-zh.github.io 随便动点什么就可以触发 Github Pages 刷新，但不知为何 Travis 部署的过程并没有触发刷新。

也许可以先试试修改 .travis.yml，使 Travis 只部署到 https://github.com/plfa-zh/plfa-zh.github.io ？

**Comment by OlingCat** [comment]
我们还是暂时只维护 https://agda-zh.github.io/PLFA-zh/ 好了，https://plfa-zh.github.io/ 直接加上 
```js
<script>
window.location='http://www.xxx.com/';
</script>
```
301 到 https://agda-zh.github.io/PLFA-zh/ 吧。
