### ISSUE TITLE
[Request] PDF版

### ISSUE THREAD

**Issue by Meowcolm024** [Agda-zh/PLFA-zh#84]
考虑到原版的PLFA并未提供官方的PDF版，请问中文翻译版能否提供官方的PDF。

**Comment by fangyi-zhou** [comment]
在构造迁移至 Hakyll 后，现有 PDF 版和 EPUB 版。然而由于 LaTeX 的问题，现在 PDF 版的渲染有问题，但是 EPUB 版可以正确显示。

https://agda-zh.github.io/PLFA-zh/plfa.epub

**Comment by fangyi-zhou** [comment]
https://agda-zh.github.io/PLFA-zh/plfa.pdf  PDF 版的字体已经修复了
